//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.01.20 at 12:25:00 PM IST
//

package com.nvarghese.beowulf.smf.scan.dto.scanrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="completed" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="pending" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "created", "completed", "pending" })
@XmlRootElement(name = "jobs")
public class Jobs {

	@XmlElement(required = true)
	protected long created;
	@XmlElement(required = true)
	protected long completed;
	@XmlElement(required = true)
	protected long pending;

	/**
	 * Gets the value of the created property.
	 * 
	 * @return possible object is {@link long }
	 * 
	 */
	public long getCreated() {

		return created;
	}

	/**
	 * Sets the value of the created property.
	 * 
	 * @param value
	 *            allowed object is {@link long }
	 * 
	 */
	public void setCreated(long value) {

		this.created = value;
	}

	/**
	 * Gets the value of the completed property.
	 * 
	 * @return possible object is {@link long }
	 * 
	 */
	public long getCompleted() {

		return completed;
	}

	/**
	 * Sets the value of the completed property.
	 * 
	 * @param value
	 *            allowed object is {@link long }
	 * 
	 */
	public void setCompleted(long value) {

		this.completed = value;
	}

	/**
	 * Gets the value of the pending property.
	 * 
	 * @return possible object is {@link long }
	 * 
	 */
	public long getPending() {

		return pending;
	}

	/**
	 * Sets the value of the pending property.
	 * 
	 * @param value
	 *            allowed object is {@link long }
	 * 
	 */
	public void setPending(long value) {

		this.pending = value;
	}

	public Jobs(long created, long completed, long pending) {

		this.created = created;
		this.completed = completed;
		this.pending = pending;
	}

	public Jobs() {

		this.created = 0;
		this.completed = 0;
		this.pending = 0;
	}

}
