//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="max_redirects" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max_consecutive_failed_requests" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max_failed_requests_per_server" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max_request_count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max_request_depth" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max_request_retries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max_spider_urls" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max_total_connections" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="socket_read_timeout" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="user_agent_string" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="character_encoding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "maxRedirects", "maxConsecutiveFailedRequests", "maxFailedRequestsPerServer", "maxRequestCount", "maxRequestDepth",
		"maxRequestRetries", "maxSpiderUrls", "maxTotalConnections", "socketReadTimeout", "userAgentString", "characterEncoding" })
@XmlRootElement(name = "http_client")
public class HttpClient {

	@XmlElement(name = "max_redirects")
	protected BigInteger maxRedirects;
	@XmlElement(name = "max_consecutive_failed_requests")
	protected BigInteger maxConsecutiveFailedRequests;
	@XmlElement(name = "max_failed_requests_per_server")
	protected BigInteger maxFailedRequestsPerServer;
	@XmlElement(name = "max_request_count")
	protected BigInteger maxRequestCount;
	@XmlElement(name = "max_request_depth")
	protected BigInteger maxRequestDepth;
	@XmlElement(name = "max_request_retries")
	protected BigInteger maxRequestRetries;
	@XmlElement(name = "max_spider_urls")
	protected BigInteger maxSpiderUrls;
	@XmlElement(name = "max_total_connections")
	protected BigInteger maxTotalConnections;
	@XmlElement(name = "socket_read_timeout")
	protected BigInteger socketReadTimeout;
	@XmlElement(name = "user_agent_string")
	protected String userAgentString;
	@XmlElement(name = "character_encoding")
	protected String characterEncoding;

	/**
	 * Gets the value of the maxRedirects property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxRedirects() {

		return maxRedirects;
	}

	/**
	 * Sets the value of the maxRedirects property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxRedirects(BigInteger value) {

		this.maxRedirects = value;
	}

	/**
	 * Gets the value of the maxConsecutiveFailedRequests property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxConsecutiveFailedRequests() {

		return maxConsecutiveFailedRequests;
	}

	/**
	 * Sets the value of the maxConsecutiveFailedRequests property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxConsecutiveFailedRequests(BigInteger value) {

		this.maxConsecutiveFailedRequests = value;
	}

	/**
	 * Gets the value of the maxFailedRequestsPerServer property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxFailedRequestsPerServer() {

		return maxFailedRequestsPerServer;
	}

	/**
	 * Sets the value of the maxFailedRequestsPerServer property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxFailedRequestsPerServer(BigInteger value) {

		this.maxFailedRequestsPerServer = value;
	}

	/**
	 * Gets the value of the maxRequestCount property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxRequestCount() {

		return maxRequestCount;
	}

	/**
	 * Sets the value of the maxRequestCount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxRequestCount(BigInteger value) {

		this.maxRequestCount = value;
	}

	/**
	 * Gets the value of the maxRequestDepth property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxRequestDepth() {

		return maxRequestDepth;
	}

	/**
	 * Sets the value of the maxRequestDepth property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxRequestDepth(BigInteger value) {

		this.maxRequestDepth = value;
	}

	/**
	 * Gets the value of the maxRequestRetries property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxRequestRetries() {

		return maxRequestRetries;
	}

	/**
	 * Sets the value of the maxRequestRetries property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxRequestRetries(BigInteger value) {

		this.maxRequestRetries = value;
	}

	/**
	 * Gets the value of the maxSpiderUrls property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxSpiderUrls() {

		return maxSpiderUrls;
	}

	/**
	 * Sets the value of the maxSpiderUrls property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxSpiderUrls(BigInteger value) {

		this.maxSpiderUrls = value;
	}

	/**
	 * Gets the value of the maxTotalConnections property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxTotalConnections() {

		return maxTotalConnections;
	}

	/**
	 * Sets the value of the maxTotalConnections property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxTotalConnections(BigInteger value) {

		this.maxTotalConnections = value;
	}

	/**
	 * Gets the value of the socketReadTimeout property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSocketReadTimeout() {

		return socketReadTimeout;
	}

	/**
	 * Sets the value of the socketReadTimeout property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSocketReadTimeout(BigInteger value) {

		this.socketReadTimeout = value;
	}

	/**
	 * Gets the value of the userAgentString property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUserAgentString() {

		return userAgentString;
	}

	/**
	 * Sets the value of the userAgentString property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUserAgentString(String value) {

		this.userAgentString = value;
	}

	/**
	 * Gets the value of the characterEncoding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCharacterEncoding() {

		return characterEncoding;
	}

	/**
	 * Sets the value of the characterEncoding property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCharacterEncoding(String value) {

		this.characterEncoding = value;
	}

}
