//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username_field_pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password_field_pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "username", "password", "usernameFieldPattern", "passwordFieldPattern" })
@XmlRootElement(name = "login")
public class Login {

	@XmlElement(required = true)
	protected String username;
	@XmlElement(required = true)
	protected String password;
	@XmlElement(name = "username_field_pattern", required = true)
	protected String usernameFieldPattern;
	@XmlElement(name = "password_field_pattern", required = true)
	protected String passwordFieldPattern;

	/**
	 * Gets the value of the username property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUsername() {

		return username;
	}

	/**
	 * Sets the value of the username property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUsername(String value) {

		this.username = value;
	}

	/**
	 * Gets the value of the password property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassword() {

		return password;
	}

	/**
	 * Sets the value of the password property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPassword(String value) {

		this.password = value;
	}

	/**
	 * Gets the value of the usernameFieldPattern property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUsernameFieldPattern() {

		return usernameFieldPattern;
	}

	/**
	 * Sets the value of the usernameFieldPattern property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUsernameFieldPattern(String value) {

		this.usernameFieldPattern = value;
	}

	/**
	 * Gets the value of the passwordFieldPattern property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPasswordFieldPattern() {

		return passwordFieldPattern;
	}

	/**
	 * Sets the value of the passwordFieldPattern property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPasswordFieldPattern(String value) {

		this.passwordFieldPattern = value;
	}

}
