//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="min_severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auto_report_generation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "filename", "minSeverity", "autoReportGeneration", "format" })
@XmlRootElement(name = "report_settings")
public class ReportSettings {

	@XmlElement(required = true)
	protected String filename;
	@XmlElement(name = "min_severity", required = true)
	protected String minSeverity;
	@XmlElement(name = "auto_report_generation")
	protected boolean autoReportGeneration;
	@XmlElement(required = true)
	protected String format;

	/**
	 * Gets the value of the filename property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFilename() {

		return filename;
	}

	/**
	 * Sets the value of the filename property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFilename(String value) {

		this.filename = value;
	}

	/**
	 * Gets the value of the minSeverity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMinSeverity() {

		return minSeverity;
	}

	/**
	 * Sets the value of the minSeverity property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMinSeverity(String value) {

		this.minSeverity = value;
	}

	/**
	 * Gets the value of the autoReportGeneration property.
	 * 
	 */
	public boolean isAutoReportGeneration() {

		return autoReportGeneration;
	}

	/**
	 * Sets the value of the autoReportGeneration property.
	 * 
	 */
	public void setAutoReportGeneration(boolean value) {

		this.autoReportGeneration = value;
	}

	/**
	 * Gets the value of the format property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFormat() {

		return format;
	}

	/**
	 * Sets the value of the format property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFormat(String value) {

		this.format = value;
	}

}
