//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="override_threshold" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="test_all_directories" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="use_automatic_overrides" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "overrideThreshold", "testAllDirectories", "useAutomaticOverrides" })
@XmlRootElement(name = "response_code_overrides")
public class ResponseCodeOverrides {

	@XmlElement(name = "override_threshold", required = true)
	protected BigInteger overrideThreshold;
	@XmlElement(name = "test_all_directories")
	protected boolean testAllDirectories;
	@XmlElement(name = "use_automatic_overrides")
	protected boolean useAutomaticOverrides;

	/**
	 * Gets the value of the overrideThreshold property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getOverrideThreshold() {

		return overrideThreshold;
	}

	/**
	 * Sets the value of the overrideThreshold property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setOverrideThreshold(BigInteger value) {

		this.overrideThreshold = value;
	}

	/**
	 * Gets the value of the testAllDirectories property.
	 * 
	 */
	public boolean isTestAllDirectories() {

		return testAllDirectories;
	}

	/**
	 * Sets the value of the testAllDirectories property.
	 * 
	 */
	public void setTestAllDirectories(boolean value) {

		this.testAllDirectories = value;
	}

	/**
	 * Gets the value of the useAutomaticOverrides property.
	 * 
	 */
	public boolean isUseAutomaticOverrides() {

		return useAutomaticOverrides;
	}

	/**
	 * Sets the value of the useAutomaticOverrides property.
	 * 
	 */
	public void setUseAutomaticOverrides(boolean value) {

		this.useAutomaticOverrides = value;
	}

}
