//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}forbidden_parameter_names"/>
 *         &lt;element ref="{}irrelevant_parameter_names"/>
 *         &lt;element ref="{}forbidden_mime_types"/>
 *         &lt;element ref="{}url_blacklist"/>
 *         &lt;element ref="{}url_whitelist"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "forbiddenParameterNames", "irrelevantParameterNames", "forbiddenMimeTypes", "urlBlacklist", "urlWhitelist" })
@XmlRootElement(name = "restrictions")
public class Restrictions {

	@XmlElement(name = "forbidden_parameter_names", required = true)
	protected ForbiddenParameterNames forbiddenParameterNames;
	@XmlElement(name = "irrelevant_parameter_names", required = true)
	protected IrrelevantParameterNames irrelevantParameterNames;
	@XmlElement(name = "forbidden_mime_types", required = true)
	protected ForbiddenMimeTypes forbiddenMimeTypes;
	@XmlElement(name = "url_blacklist", required = true)
	protected UrlBlacklist urlBlacklist;
	@XmlElement(name = "url_whitelist", required = true)
	protected UrlWhitelist urlWhitelist;

	/**
	 * Gets the value of the forbiddenParameterNames property.
	 * 
	 * @return possible object is {@link ForbiddenParameterNames }
	 * 
	 */
	public ForbiddenParameterNames getForbiddenParameterNames() {

		return forbiddenParameterNames;
	}

	/**
	 * Sets the value of the forbiddenParameterNames property.
	 * 
	 * @param value
	 *            allowed object is {@link ForbiddenParameterNames }
	 * 
	 */
	public void setForbiddenParameterNames(ForbiddenParameterNames value) {

		this.forbiddenParameterNames = value;
	}

	/**
	 * Gets the value of the irrelevantParameterNames property.
	 * 
	 * @return possible object is {@link IrrelevantParameterNames }
	 * 
	 */
	public IrrelevantParameterNames getIrrelevantParameterNames() {

		return irrelevantParameterNames;
	}

	/**
	 * Sets the value of the irrelevantParameterNames property.
	 * 
	 * @param value
	 *            allowed object is {@link IrrelevantParameterNames }
	 * 
	 */
	public void setIrrelevantParameterNames(IrrelevantParameterNames value) {

		this.irrelevantParameterNames = value;
	}

	/**
	 * Gets the value of the forbiddenMimeTypes property.
	 * 
	 * @return possible object is {@link ForbiddenMimeTypes }
	 * 
	 */
	public ForbiddenMimeTypes getForbiddenMimeTypes() {

		return forbiddenMimeTypes;
	}

	/**
	 * Sets the value of the forbiddenMimeTypes property.
	 * 
	 * @param value
	 *            allowed object is {@link ForbiddenMimeTypes }
	 * 
	 */
	public void setForbiddenMimeTypes(ForbiddenMimeTypes value) {

		this.forbiddenMimeTypes = value;
	}

	/**
	 * Gets the value of the urlBlacklist property.
	 * 
	 * @return possible object is {@link UrlBlacklist }
	 * 
	 */
	public UrlBlacklist getUrlBlacklist() {

		return urlBlacklist;
	}

	/**
	 * Sets the value of the urlBlacklist property.
	 * 
	 * @param value
	 *            allowed object is {@link UrlBlacklist }
	 * 
	 */
	public void setUrlBlacklist(UrlBlacklist value) {

		this.urlBlacklist = value;
	}

	/**
	 * Gets the value of the urlWhitelist property.
	 * 
	 * @return possible object is {@link UrlWhitelist }
	 * 
	 */
	public UrlWhitelist getUrlWhitelist() {

		return urlWhitelist;
	}

	/**
	 * Sets the value of the urlWhitelist property.
	 * 
	 * @param value
	 *            allowed object is {@link UrlWhitelist }
	 * 
	 */
	public void setUrlWhitelist(UrlWhitelist value) {

		this.urlWhitelist = value;
	}

}
