//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}response_code_overrides"/>
 *         &lt;element ref="{}base_uris"/>
 *         &lt;element ref="{}restrictions"/>
 *         &lt;element ref="{}import_spidered_uris"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "responseCodeOverrides", "baseUris", "restrictions", "importSpideredUris" })
@XmlRootElement(name = "scan_settings")
public class ScanSettings {

	@XmlElement(name = "response_code_overrides", required = true)
	protected ResponseCodeOverrides responseCodeOverrides;
	@XmlElement(name = "base_uris", required = true)
	protected BaseUris baseUris;
	@XmlElement(required = true)
	protected Restrictions restrictions;
	@XmlElement(name = "import_spidered_uris", required = true)
	protected ImportSpideredUris importSpideredUris;

	/**
	 * Gets the value of the responseCodeOverrides property.
	 * 
	 * @return possible object is {@link ResponseCodeOverrides }
	 * 
	 */
	public ResponseCodeOverrides getResponseCodeOverrides() {

		return responseCodeOverrides;
	}

	/**
	 * Sets the value of the responseCodeOverrides property.
	 * 
	 * @param value
	 *            allowed object is {@link ResponseCodeOverrides }
	 * 
	 */
	public void setResponseCodeOverrides(ResponseCodeOverrides value) {

		this.responseCodeOverrides = value;
	}

	/**
	 * Gets the value of the baseUris property.
	 * 
	 * @return possible object is {@link BaseUris }
	 * 
	 */
	public BaseUris getBaseUris() {

		return baseUris;
	}

	/**
	 * Sets the value of the baseUris property.
	 * 
	 * @param value
	 *            allowed object is {@link BaseUris }
	 * 
	 */
	public void setBaseUris(BaseUris value) {

		this.baseUris = value;
	}

	/**
	 * Gets the value of the restrictions property.
	 * 
	 * @return possible object is {@link Restrictions }
	 * 
	 */
	public Restrictions getRestrictions() {

		return restrictions;
	}

	/**
	 * Sets the value of the restrictions property.
	 * 
	 * @param value
	 *            allowed object is {@link Restrictions }
	 * 
	 */
	public void setRestrictions(Restrictions value) {

		this.restrictions = value;
	}

	/**
	 * Gets the value of the importSpideredUris property.
	 * 
	 * @return possible object is {@link ImportSpideredUris }
	 * 
	 */
	public ImportSpideredUris getImportSpideredUris() {

		return importSpideredUris;
	}

	/**
	 * Sets the value of the importSpideredUris property.
	 * 
	 * @param value
	 *            allowed object is {@link ImportSpideredUris }
	 * 
	 */
	public void setImportSpideredUris(ImportSpideredUris value) {

		this.importSpideredUris = value;
	}

}
