//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="use_logged_out_detection" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{}known_session_idlist"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "useLoggedOutDetection", "knownSessionIdlist" })
@XmlRootElement(name = "session_tracking")
public class SessionTracking {

	@XmlElement(name = "use_logged_out_detection")
	protected boolean useLoggedOutDetection;
	@XmlElement(name = "known_session_idlist", required = true)
	protected KnownSessionIdlist knownSessionIdlist;

	/**
	 * Gets the value of the useLoggedOutDetection property.
	 * 
	 */
	public boolean isUseLoggedOutDetection() {

		return useLoggedOutDetection;
	}

	/**
	 * Sets the value of the useLoggedOutDetection property.
	 * 
	 */
	public void setUseLoggedOutDetection(boolean value) {

		this.useLoggedOutDetection = value;
	}

	/**
	 * Gets the value of the knownSessionIdlist property.
	 * 
	 * @return possible object is {@link KnownSessionIdlist }
	 * 
	 */
	public KnownSessionIdlist getKnownSessionIdlist() {

		return knownSessionIdlist;
	}

	/**
	 * Sets the value of the knownSessionIdlist property.
	 * 
	 * @param value
	 *            allowed object is {@link KnownSessionIdlist }
	 * 
	 */
	public void setKnownSessionIdlist(KnownSessionIdlist value) {

		this.knownSessionIdlist = value;
	}

}
