//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.10.01 at 01:12:11 AM IST
//

package com.nvarghese.beowulf.common.scan.dto.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}login"/>
 *         &lt;element ref="{}session_tracking"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "login", "sessionTracking" })
@XmlRootElement(name = "session_settings")
public class SessionSettings {

	@XmlElement(required = true)
	protected Login login;
	@XmlElement(name = "session_tracking", required = true)
	protected SessionTracking sessionTracking;

	/**
	 * Gets the value of the login property.
	 * 
	 * @return possible object is {@link Login }
	 * 
	 */
	public Login getLogin() {

		return login;
	}

	/**
	 * Sets the value of the login property.
	 * 
	 * @param value
	 *            allowed object is {@link Login }
	 * 
	 */
	public void setLogin(Login value) {

		this.login = value;
	}

	/**
	 * Gets the value of the sessionTracking property.
	 * 
	 * @return possible object is {@link SessionTracking }
	 * 
	 */
	public SessionTracking getSessionTracking() {

		return sessionTracking;
	}

	/**
	 * Sets the value of the sessionTracking property.
	 * 
	 * @param value
	 *            allowed object is {@link SessionTracking }
	 * 
	 */
	public void setSessionTracking(SessionTracking value) {

		this.sessionTracking = value;
	}

}
