//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.01.20 at 12:25:00 PM IST
//

package com.nvarghese.beowulf.smf.scan.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface
 * 
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Comment_QNAME = new QName("", "comment");
	private final static QName _Baseuri_QNAME = new QName("", "baseuri");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * 
	 * 
	 */
	public ObjectFactory() {

	}

	/**
	 * Create an instance of {@link Comments }
	 * 
	 */
	public Comments createComments() {

		return new Comments();
	}

	/**
	 * Create an instance of {@link Baseuris }
	 * 
	 */
	public Baseuris createBaseuris() {

		return new Baseuris();
	}

	/**
	 * Create an instance of {@link ScanRequest }
	 * 
	 */
	public ScanRequest createScanRequest() {

		return new ScanRequest();
	}

	/**
	 * Create an instance of {@link Jobs }
	 * 
	 */
	public Jobs createJobs() {

		return new Jobs();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "comment")
	public JAXBElement<String> createComment(String value) {

		return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "baseuri")
	public JAXBElement<String> createBaseuri(String value) {

		return new JAXBElement<String>(_Baseuri_QNAME, String.class, null, value);
	}

}
