//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.01.20 at 12:25:00 PM IST
//

package com.nvarghese.beowulf.smf.scan.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scanphase" type="{http://www.w3.org/2001/XMLSchema}string"/> *         
 *         &lt;element ref="{}baseuris"/>
 *         &lt;element name="startedtime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="endtime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="estimatedtime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="percentagedone" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{}jobs"/>
 *         &lt;element ref="{}comments"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"id",
		"scanphase",		
		"baseuris",
		"startedtime",
		"endtime",
		"estimatedtime",
		"percentagedone",
		"jobs",
		"comments" 
		})
@XmlRootElement(name = "scanrequest")
public class ScanRequest {

	@XmlElement(required = true)
	protected String id;
	@XmlElement(required = true)
	protected String scanphase;
	@XmlElement(required = true)
	protected Baseuris baseuris;
	@XmlElement(required = true)
	protected long startedtime;
	@XmlElement(required = true)
	protected long endtime;
	@XmlElement(required = true)
	protected long estimatedtime;
	@XmlElement(required = true)
	protected int percentagedone;
	@XmlElement(required = true)
	protected Jobs jobs;
	@XmlElement(required = true)
	protected Comments comments;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {

		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {

		this.id = value;
	}

	/**
	 * Gets the value of the scanphase property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScanphase() {

		return scanphase;
	}

	/**
	 * Sets the value of the scanphase property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScanphase(String value) {

		this.scanphase = value;
	}



	/**
	 * Gets the value of the baseuris property.
	 * 
	 * @return possible object is {@link Baseuris }
	 * 
	 */
	public Baseuris getBaseuris() {

		return baseuris;
	}

	/**
	 * Sets the value of the baseuris property.
	 * 
	 * @param value
	 *            allowed object is {@link Baseuris }
	 * 
	 */
	public void setBaseuris(Baseuris value) {

		this.baseuris = value;
	}

	/**
	 * Gets the value of the startedtime property.
	 * 
	 */
	public long getStartedtime() {

		return startedtime;
	}

	/**
	 * Sets the value of the startedtime property.
	 * 
	 */
	public void setStartedtime(long value) {

		this.startedtime = value;
	}

	/**
	 * Gets the value of the endtime property.
	 * 
	 */
	public long getEndtime() {

		return endtime;
	}

	/**
	 * Sets the value of the endtime property.
	 * 
	 */
	public void setEndtime(long value) {

		this.endtime = value;
	}
	/**
	 * Gets the value of the estimatedtime property.
	 * 
	 */
	public long getEstimatedtime() {

		return estimatedtime;
	}

	/**
	 * Sets the value of the estimatedtime property.
	 * 
	 */
	public void setEstimatedtime(long value) {

		this.estimatedtime = value;
	}

	/**
	 * Gets the value of the percentagedone property.
	 * 
	 * @return possible object is {@link int }
	 * 
	 */
	public int getPercentagedone() {

		return percentagedone;
	}

	/**
	 * Sets the value of the percentagedone property.
	 * 
	 * @param value
	 *            allowed object is {@link int }
	 * 
	 */
	public void setPercentagedone(int value) {

		this.percentagedone = value;
	}

	/**
	 * Gets the value of the jobs property.
	 * 
	 * @return possible object is {@link Jobs }
	 * 
	 */
	public Jobs getJobs() {

		return jobs;
	}

	/**
	 * Sets the value of the jobs property.
	 * 
	 * @param value
	 *            allowed object is {@link Jobs }
	 * 
	 */
	public void setJobs(Jobs value) {

		this.jobs = value;
	}

	/**
	 * Gets the value of the comments property.
	 * 
	 * @return possible object is {@link Comments }
	 * 
	 */
	public Comments getComments() {

		return comments;
	}

	/**
	 * Sets the value of the comments property.
	 * 
	 * @param value
	 *            allowed object is {@link Comments }
	 * 
	 */
	public void setComments(Comments value) {

		this.comments = value;
	}

}
