package com.nvarghese.beowulf.common.webtest;

public enum WebTestType {

		DIRECTORY_TEST,
		FILE_TEST,
		HOST_TEST,
		HTML_ELEM_TEST,
		HTTP_METHOD_TEST,
		HTTP_QUERY_PARAM_TEST,
		HTTP_RESPONSE_CODE_TEST,
		HTTP_MIME_TEST,
		OUTPUT_CONTEXT_TEST,
		REPEATABLE_OUTPUT_CONTEXT_TEST,
		HTTP_REQUEST_HEADER_TEST,
		HTTP_RESPONSE_HEADER_TEST,
		HTTP_SET_COOKIE_HEADER_TEST;

}
